server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # SPA routing
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy /api para o backend Frappe
    location /api {
        proxy_pass https://beta.shapefy.online;
        proxy_set_header Host beta.shapefy.online;
        proxy_ssl_server_name on;
    }
}
